init:
  - git config --global core.autocrlf input

shallow_clone: true

version: '{build}'

environment:
  matrix:
    - nodejs_version: '1.2'
    - nodejs_version: '0.12'

install:
  - ps: Install-Product node $env:nodejs_version
  - npm install --production
  - npm install tape

build: off

test_script:
  - ps: 'node test-api.js # PowerShell'
  - ps: 'node test-cli.js # PowerShell'
  - cmd: node test-api.js
  - cmd: node test-cli.js

cache:
  - node_modules
